variable "network_interface_name" {}
variable "network_interface_location" {}
variable "resource_group_name" {}
variable "linux_virtual_machine_name" {}
variable "linux_virtual_machine_location" {}
variable "admin_username_name" {}
variable "admin_password_name" {}
variable "publisher_image" {}
variable "offer_image" {}
variable "sku_image" {}
variable "version_image" {}
variable "subnet_name" {}
variable "virtual_network_name" {}
variable "resource_nsg_name" {}