name: "evo-ecom-webaap-infra"

on:  workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs: 
  terraforn_init_plan:
    runs-on: HP
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: 66d78909-4289-443a-82ed-eb67f5b3842e
          tenant-id: 87fec6fb-a2ea-4f38-bee7-2555182f058e
          subscription-id: 51984565-3b14-41c7-900f-cf01ff601798
          


       

       
