name: "evo-ecom-webaap-infra"

on:  workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs: 
  terraforn_init_plan:
    runs-on: HP
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: 38132e7c-ec7a-4dc6-8b74-e31bc76e8d87
          tenant-id: 81f0c137-86a5-4142-9cf3-7d808cea78b1
          subscription-id: 51984565-3b14-41c7-900f-cf01ff601798
          


       

       
